"""Gaussian Mixture Model (GMM) clustering adapter (ML-05).

This module implements Gaussian Mixture Model as a concrete
:class:`BaseClusterAlgorithm` adapter that plugs into the ML-01
experiment framework. GMM is the model-based / probabilistic
clustering family member of the EPIC-06 benchmark set.

The adapter is a **thin, value-neutral wrapper** around
``sklearn.mixture.GaussianMixture``. It does NOT:

- evaluate the result (silhouette, DBI, CH are EPIC-07/08 scope);
- compare GMM to other algorithms (EPIC-08 scope);
- pick the "best" ``n_components``, ``covariance_type``, or
  initialization (EPIC-07 scope);
- use AIC / BIC / log-likelihood to declare a "best" configuration
  (model-selection sweep belongs to EPIC-07);
- transform, scale, or impute the input (FE-06 scope);
- mutate the input matrix.

The adapter exposes the GMM hyperparameters explicitly listed in
the ML-05 task contract: ``n_components``, ``covariance_type``,
``init_params`` and ``random_state``. Optional convergence-related
parameters (``tol``, ``reg_covar``, ``max_iter``, ``n_init``) are
also accepted so the adapter can be tuned within ML-05's diagnostic
scope; they are NOT promoted as final research methodology by this
adapter.

Hard constraints (AGENTS.md §2, §3 "Clustering"):

- No "best/recommended/optimal/winner" language.
- The adapter MUST NOT mutate the input matrix ``X``.
- The adapter MUST NOT compute evaluation metrics (silhouette,
  DBI, CH, ...).
- The adapter MUST NOT remove or relabel observations.
- The adapter MUST preserve the soft-clustering output (per-sample
  posterior responsibilities) — this is the defining characteristic
  of model-based clustering and MUST be exposed via
  :attr:`ClusterResult.soft_probabilities` and the
  ``algorithm_output`` artifact.
- The adapter MUST respect the random-state policy of ML-01:
  GMM consumes ``random_state`` for initialization; the adapter
  advertises :meth:`supports_random_state` as ``True`` so the
  framework can inject a seed.

Methodology background
----------------------

**Gaussian Mixture Model** assumes the data is generated by a
weighted sum of multivariate Gaussian distributions. Given an
observation ``x``,

    p(x) = Σ_{k=1..K} π_k · N(x | μ_k, Σ_k)

where:

- ``K`` is the number of components (``n_components``);
- ``π_k >= 0`` and ``Σ_k π_k = 1`` are the mixture weights
  (``weights_`` after fit);
- ``μ_k ∈ ℝ^p`` is the mean vector of component ``k``
  (``means_`` after fit);
- ``Σ_k`` is the covariance matrix of component ``k``
  (``covariances_`` after fit).

**Hard cluster label** of observation ``x_i``:

    c_i = argmax_k P(z_i = k | x_i)

where ``z_i`` is the latent cluster indicator. sklearn's
``GaussianMixture.predict`` returns this argmax.

**Soft assignment** — **posterior responsibility** — of component
``k`` for observation ``x_i``:

    γ_ik = P(z_i = k | x_i)
         = [π_k · N(x_i | μ_k, Σ_k)] / [Σ_j π_j · N(x_i | μ_j, Σ_j)]

sklearn's ``GaussianMixture.predict_proba`` returns the
responsibility matrix of shape ``(n_samples, n_components)``.
Each row sums to 1 in exact arithmetic (modulo float precision).

**Expectation-Maximization (EM)** is the algorithm sklearn uses to
fit the parameters ``θ = {π_k, μ_k, Σ_k}_{k=1..K}`` by maximizing
the observed-data log-likelihood:

    L(θ) = Σ_i log p(x_i | θ)
         = Σ_i log [Σ_k π_k · N(x_i | μ_k, Σ_k)]

EM alternates:

- **E-step**: compute responsibilities ``γ_ik`` given the current
  parameters.
- **M-step**: update ``π_k``, ``μ_k``, ``Σ_k`` to maximise the
  expected complete-data log-likelihood under the current
  responsibilities.

EM converges monotonically (non-decreasing log-likelihood) but only
to a local maximum. The lower bound
``model.lower_bound_`` is the (negative of the) training
log-likelihood on the training data plus a constant; it is reported
as the model-fitting objective (NOT a clustering quality metric).

**Initialization**:

- ``init_params="kmeans"`` (default in sklearn) runs a K-Means
  pass to seed means, then derives the rest of the parameters.
- ``init_params="random"`` samples responsibilities from a uniform
  Dirichlet distribution and computes initial means / covariances /
  weights.

Both initialization paths consume ``random_state`` for
reproducibility.

**Covariance type** controls the shape of ``Σ_k``:

- ``"full"``: each component has its own general covariance
  matrix (most flexible; most parameters).
- ``"tied"``: all components share a single general covariance
  matrix (intermediate parameters).
- ``"diag"``: each component has its own diagonal covariance
  matrix (no feature-correlation terms).
- ``"spherical"``: each component has a single variance scalar
  (fewest parameters).

The choice of covariance type is a **methodology decision** owned
by EPIC-07; this adapter accepts all four sklearn options and
records the chosen type in :attr:`ClusterResult.extra`.

**Model-selection helpers** — AIC and BIC — are exposed in
``model.aic(X)`` and ``model.bic(X)``. They are recorded as
algorithm-specific diagnostics only; the adapter does NOT use
them to declare a "best" configuration.

Reproducibility
---------------

GMM consumes ``random_state`` for both ``init_params="kmeans"``
(K-Means init seed) and ``init_params="random"`` (Dirichlet
responsibilities and Gaussian samples). The adapter:

- Accepts ``random_state`` in its constructor.
- Advertises :meth:`supports_random_state` returning ``True`` so
  the ML-01 runner injects the framework's seed.
- Records ``random_seed_used`` truthfully.

GMM has a known **label permutation** property: the
``k``-th component after fit is not necessarily the same as the
``k``-th component across different runs (even with the same
seed, if convergence lands in different local maxima). Therefore
raw label equality is NOT a reliable reproducibility check. The
adapter exposes:

- The posterior responsibility matrix
  (:attr:`ClusterResult.soft_probabilities`).
- The component means (``means_``) and mixture weights
  (``weights_``).
- The log-likelihood lower bound (``lower_bound_``).

…so that downstream reproducibility checks can compare
permutation-invariant quantities rather than raw labels.

Algorithm-specific diagnostics (ML-05 scope)
-------------------------------------------

The adapter records the following GMM-specific diagnostics in
:attr:`ClusterResult.extra`:

- ``n_components``, ``covariance_type``, ``init_params``,
  ``random_state``.
- ``converged`` (bool) — whether EM hit the convergence
  criterion within ``max_iter``.
- ``n_iter`` (int) — number of EM iterations actually used.
- ``lower_bound`` (float) — sklearn's ``model.lower_bound_``.
- ``aic`` (float), ``bic`` (float) — model-selection helpers
  recorded as diagnostics only.
- ``mixture_weights`` (list of float) — ``model.weights_``.
- ``cluster_sizes`` (dict label → count) — derived from hard
  labels (NOT the soft responsibilities).
- ``soft_probabilities_shape`` (list) — ``(n_samples,
  n_components)``.
- ``soft_probabilities_row_sum_min`` / ``_max`` (float) —
  diagnostics for row-sum integrity.
- ``responsibility_max_probability_min`` / ``_max`` /
  ``_mean`` (float) — confidence summary.

These diagnostics are **diagnostic-only** in ML-05; EPIC-07 will
own the controlled sweep that consumes them.
"""

from __future__ import annotations

from typing import Any

import numpy as np
import sklearn
from sklearn.mixture import GaussianMixture

from customer_segmentation.clustering.base import BaseClusterAlgorithm, ClusterAlgorithmError
from customer_segmentation.clustering.registry import AlgorithmRegistry
from customer_segmentation.clustering.result import AlgorithmFamily, ClusterResult

__all__ = [
    "GMMAdapter",
    "DEFAULT_COVARIANCE_TYPE",
    "DEFAULT_INIT_PARAMS",
    "DEFAULT_TOL",
    "DEFAULT_REG_COVAR",
    "DEFAULT_MAX_ITER",
    "DEFAULT_N_INIT",
    "MIN_N_COMPONENTS",
    "SUPPORTED_COVARIANCE_TYPES",
    "SUPPORTED_INIT_PARAMS",
]


# ---------------------------------------------------------------------------
# Working defaults (mirror configs/clustering.yaml algorithms.gmm.*).
# These are *working* defaults (TECHNICALLY_IMPLEMENTED), not final approved
# methodology. EPIC-07 will run the controlled sweep over n_components /
# covariance_type / init_params.
# ---------------------------------------------------------------------------

DEFAULT_COVARIANCE_TYPE: str = "full"
DEFAULT_INIT_PARAMS: str = "kmeans"
DEFAULT_TOL: float = 1e-3
DEFAULT_REG_COVAR: float = 1e-6
DEFAULT_MAX_ITER: int = 100
DEFAULT_N_INIT: int = 1
MIN_N_COMPONENTS: int = 1

# sklearn-supported covariance types.
SUPPORTED_COVARIANCE_TYPES: frozenset[str] = frozenset({"full", "tied", "diag", "spherical"})

# sklearn-supported initialization strategies for init_params.
SUPPORTED_INIT_PARAMS: frozenset[str] = frozenset({"kmeans", "random"})


@AlgorithmRegistry.register("gmm")
class GMMAdapter(BaseClusterAlgorithm):
    """Gaussian Mixture Model adapter for ML-01 framework.

    The adapter wraps ``sklearn.mixture.GaussianMixture``. It does
    NOT transform, scale, or impute the input — that is FE-06's
    job.

    Attributes
    ----------
    name : str
        Stable, lowercase identifier (``"gmm"``). Set by the
        registry on registration.
    version : str
        ``"sklearn_<version>"`` so the experiment log captures the
        underlying library version.
    family : str
        :attr:`AlgorithmFamily.MODEL_BASED` — GMM produces soft
        posterior responsibilities and a derived hard label.

    Parameters
    ----------
    n_components : int
        Number of Gaussian components ``K``. Must be ``>= 1``.
        Working default is **not set here** — ML-05 must always
        receive an explicit ``n_components`` from the caller /
        EPIC-07 sweep.
    covariance_type : str
        Shape of each component's covariance matrix. One of
        ``"full"`` (default), ``"tied"``, ``"diag"``,
        ``"spherical"``.
    init_params : str
        Initialization strategy for EM. One of ``"kmeans"``
        (default) or ``"random"``.
    random_state : int or None
        Seed for the random number generator. The framework may
        pass an explicit seed via ``resolve_random_seed``.
    tol : float
        Convergence threshold passed through to sklearn. Default
        ``1e-3`` (sklearn default).
    reg_covar : float
        Regularisation added to covariance diagonals. Default
        ``1e-6`` (sklearn default).
    max_iter : int
        Maximum number of EM iterations. Default ``100`` (sklearn
        default).
    n_init : int
        Number of initialisations (each with a different seed)
        from which the best fit is selected by lower bound.
        Default ``1`` (sklearn default).

    Notes
    -----
    - The adapter does NOT mutate the input matrix ``X``.
    - The adapter records soft probabilities in
      :attr:`ClusterResult.soft_probabilities`; the framework's
      artifact writer emits ``Probability_k`` columns in both the
      labels parquet and a separate ``algorithm_output`` parquet.
    - The adapter records convergence diagnostics, mixture
      weights, lower bound, AIC, BIC, cluster sizes and
      responsibility statistics in :attr:`ClusterResult.extra`.
    - The adapter does NOT compute silhouette, Davies-Bouldin,
      or Calinski-Harabasz indices (out of scope).
    - The adapter DOES consume ``random_state``; the runner
      injects the framework seed.
    - Label permutation between components is possible across
      runs (even with the same seed, depending on local maxima);
      raw label equality is NOT a reliable reproducibility
      assertion. Use responsibilities, means, lower bound, or
      permutation-invariant comparisons instead.
    """

    name: str = "gmm"
    version: str = f"sklearn_{sklearn.__version__}"
    family: str = AlgorithmFamily.MODEL_BASED

    def __init__(
        self,
        n_components: int,
        *,
        covariance_type: str = DEFAULT_COVARIANCE_TYPE,
        init_params: str = DEFAULT_INIT_PARAMS,
        random_state: int | None = None,
        tol: float = DEFAULT_TOL,
        reg_covar: float = DEFAULT_REG_COVAR,
        max_iter: int = DEFAULT_MAX_ITER,
        n_init: int = DEFAULT_N_INIT,
    ) -> None:
        # ---- Hyperparameter validation (fail-fast on bad config) ----
        if not isinstance(n_components, (int, np.integer)):
            raise ClusterAlgorithmError(
                f"n_components must be an integer; got {type(n_components).__name__}."
            )
        if int(n_components) < MIN_N_COMPONENTS:
            raise ClusterAlgorithmError(
                f"n_components must be >= {MIN_N_COMPONENTS}; got {n_components}."
            )
        if not isinstance(covariance_type, str):
            raise ClusterAlgorithmError(
                f"covariance_type must be a string; got "
                f"{type(covariance_type).__name__}={covariance_type!r}."
            )
        if covariance_type not in SUPPORTED_COVARIANCE_TYPES:
            raise ClusterAlgorithmError(
                f"covariance_type must be one of {sorted(SUPPORTED_COVARIANCE_TYPES)}; "
                f"got {covariance_type!r}."
            )
        if not isinstance(init_params, str):
            raise ClusterAlgorithmError(
                f"init_params must be a string; got "
                f"{type(init_params).__name__}={init_params!r}."
            )
        if init_params not in SUPPORTED_INIT_PARAMS:
            raise ClusterAlgorithmError(
                f"init_params must be one of {sorted(SUPPORTED_INIT_PARAMS)}; "
                f"got {init_params!r}."
            )
        if random_state is not None and not isinstance(random_state, (int, np.integer)):
            raise ClusterAlgorithmError(
                f"random_state must be an integer or None; got "
                f"{type(random_state).__name__}={random_state!r}."
            )
        if not isinstance(tol, (int, float)) or float(tol) <= 0:
            raise ClusterAlgorithmError(f"tol must be a positive number; got {tol!r}.")
        if not isinstance(reg_covar, (int, float)) or float(reg_covar) <= 0:
            raise ClusterAlgorithmError(f"reg_covar must be a positive number; got {reg_covar!r}.")
        if not isinstance(max_iter, (int, np.integer)) or int(max_iter) < 1:
            raise ClusterAlgorithmError(f"max_iter must be a positive integer; got {max_iter!r}.")
        if not isinstance(n_init, (int, np.integer)) or int(n_init) < 1:
            raise ClusterAlgorithmError(f"n_init must be a positive integer; got {n_init!r}.")

        self.n_components = int(n_components)
        self.covariance_type = covariance_type
        self.init_params = init_params
        self.random_state = None if random_state is None else int(random_state)
        self.tol = float(tol)
        self.reg_covar = float(reg_covar)
        self.max_iter = int(max_iter)
        self.n_init = int(n_init)

        # Fitted state (populated by fit()).
        self._model: GaussianMixture | None = None

    # ----- Algorithm interface -----
    def fit(self, X: np.ndarray) -> ClusterResult:
        """Fit Gaussian Mixture Model on the feature matrix.

        Parameters
        ----------
        X : numpy.ndarray
            Numeric feature matrix of shape ``(n_samples, n_features)``.
            MUST be the matrix delivered by the framework
            (``matrix_df.to_numpy(dtype=np.float64, copy=False)``).
            MUST NOT contain identifiers (validated upstream by
            :func:`validate_clustering_matrix`).

        Returns
        -------
        ClusterResult
            Hard cluster labels derived from the fitted model,
            soft posterior responsibilities in
            :attr:`ClusterResult.soft_probabilities`, plus
            GMM-specific diagnostics (convergence, mixture weights,
            lower bound, AIC, BIC, cluster sizes) in
            :attr:`ClusterResult.extra`.

        Raises
        ------
        ClusterAlgorithmError
            If the input is invalid for GMM (e.g. wrong
            dimensionality, sklearn raises during fit, ...).
        """
        if X is None:
            raise ClusterAlgorithmError("Input matrix X is None.")
        if not isinstance(X, np.ndarray):
            raise ClusterAlgorithmError(
                f"Input matrix must be a numpy.ndarray; got {type(X).__name__}."
            )
        if X.ndim != 2:
            raise ClusterAlgorithmError(f"Input matrix must be 2-D; got ndim={X.ndim}.")
        n_samples, n_features = X.shape
        if n_samples < 1:
            raise ClusterAlgorithmError(f"GMM requires n_samples >= 1; got n_samples={n_samples}.")
        if n_features < 1:
            raise ClusterAlgorithmError(
                f"GMM requires n_features >= 1; got n_features={n_features}."
            )
        # sklearn allows n_components up to n_samples; we mirror that
        # to keep the framework consistent with sklearn's own contract.

        # Build the GaussianMixture estimator. We do NOT pass a
        # pre-existing model; we construct a fresh one each fit.
        try:
            model = GaussianMixture(
                n_components=self.n_components,
                covariance_type=self.covariance_type,
                init_params=self.init_params,
                random_state=self.random_state,
                tol=self.tol,
                reg_covar=self.reg_covar,
                max_iter=self.max_iter,
                n_init=self.n_init,
            )
            model.fit(X)
        except ValueError as exc:
            # sklearn raises ValueError for impossible configurations
            # (e.g. covariance_type unknown, n_components invalid).
            raise ClusterAlgorithmError(f"GMM fit failed: {exc}") from exc
        except TypeError as exc:
            # Some sklearn versions raise TypeError for unknown kwargs.
            raise ClusterAlgorithmError(f"GMM fit failed: {exc}") from exc
        except Exception as exc:  # noqa: BLE001 - convert any sklearn error
            raise ClusterAlgorithmError(f"GMM fit failed: {exc}") from exc

        # ---- Hard labels (argmax over responsibilities) ----
        try:
            labels_array = model.predict(X)
        except Exception as exc:  # noqa: BLE001 - defensive
            raise ClusterAlgorithmError(f"GMM predict failed: {exc}") from exc

        labels = np.asarray(labels_array, dtype=np.int64)

        # ---- Soft responsibilities (posterior probabilities) ----
        try:
            responsibilities = np.asarray(model.predict_proba(X), dtype=np.float64)
        except Exception as exc:  # noqa: BLE001 - defensive
            raise ClusterAlgorithmError(f"GMM predict_proba failed: {exc}") from exc

        # Cache the fitted model so callers can introspect via
        # get_model().
        self._model = model

        # ---- Convergence and likelihood diagnostics ----
        converged = bool(getattr(model, "converged_", False))
        n_iter = int(getattr(model, "n_iter_", 0))
        lower_bound = float(getattr(model, "lower_bound_", float("nan")))
        try:
            aic_value = float(model.aic(X))
        except Exception:  # pragma: no cover - defensive
            aic_value = None
        try:
            bic_value = float(model.bic(X))
        except Exception:  # pragma: no cover - defensive
            bic_value = None

        # Mixture weights and component sizes (from hard labels).
        try:
            mixture_weights = [float(w) for w in np.asarray(model.weights_).tolist()]
        except Exception:  # pragma: no cover - defensive
            mixture_weights = []

        cluster_sizes: dict[str, int] = {}
        for lbl in np.unique(labels):
            cluster_sizes[str(int(lbl))] = int((labels == lbl).sum())

        # Responsibility integrity diagnostics.
        row_sums = responsibilities.sum(axis=1)
        max_probs = responsibilities.max(axis=1)

        # n_clusters == n_components by definition for a fitted GMM.
        n_clusters_found = int(self.n_components)

        extra: dict[str, Any] = {
            # Configuration echo.
            "n_components": int(self.n_components),
            "covariance_type": str(self.covariance_type),
            "init_params": str(self.init_params),
            "random_state": (None if self.random_state is None else int(self.random_state)),
            "tol": float(self.tol),
            "reg_covar": float(self.reg_covar),
            "max_iter": int(self.max_iter),
            "n_init": int(self.n_init),
            # Convergence.
            "converged": converged,
            "n_iter": n_iter,
            # Model-fitting objective (NOT a clustering quality metric).
            "lower_bound": lower_bound,
            # Model-selection helpers recorded as diagnostics only.
            "aic": aic_value,
            "bic": bic_value,
            # Mixture parameters.
            "mixture_weights": mixture_weights,
            # Cluster sizes derived from hard labels.
            "cluster_sizes": cluster_sizes,
            # Soft clustering metadata (without serialising the full
            # responsibility matrix into the experiment log).
            "soft_probabilities_shape": list(responsibilities.shape),
            "soft_probabilities_row_sum_min": float(row_sums.min()),
            "soft_probabilities_row_sum_max": float(row_sums.max()),
            "responsibility_max_probability_min": float(max_probs.min()),
            "responsibility_max_probability_max": float(max_probs.max()),
            "responsibility_max_probability_mean": float(max_probs.mean()),
        }

        return ClusterResult(
            algorithm=self.name,
            algorithm_version=self.version,
            algorithm_family=self.family,
            n_samples=int(n_samples),
            n_features=int(n_features),
            cluster_labels=labels,
            n_clusters=n_clusters_found,
            # GMM soft clustering output: full responsibility matrix.
            # The framework's artifact writer emits ``Probability_k``
            # columns in both the cluster_labels parquet and a
            # separate ``algorithm_output`` parquet for downstream
            # consumers (EPIC-07/08/09).
            soft_probabilities=responsibilities,
            # GMM has no dedicated noise label; leave default -1
            # (the framework does NOT interpret GMM labels as noise).
            noise_label=-1,
            noise_count=0,
            noise_ratio=0.0,
            supports_random_state=True,
            random_seed_used=self.random_state,
            extra=extra,
            # metrics placeholder stays default (all None) — EPIC-07/08
            # will populate.
        )

    # ----- Convenience hooks -----
    def get_params(self) -> dict[str, Any]:
        """Return the adapter's hyperparameters as a JSON-friendly dict.

        Override the base default to expose the explicit
        hyperparameters used by GMM. The framework records this in
        the experiment log so future readers can reproduce the exact
        configuration.
        """
        return {
            "n_components": self.n_components,
            "covariance_type": str(self.covariance_type),
            "init_params": str(self.init_params),
            "random_state": self.random_state,
            "tol": self.tol,
            "reg_covar": self.reg_covar,
            "max_iter": self.max_iter,
            "n_init": self.n_init,
        }

    def get_model(self) -> Any:
        """Return the underlying fitted ``sklearn.mixture.GaussianMixture``.

        Returns ``None`` if :meth:`fit` has not been called yet. This
        hook lets EPIC-07/08 introspect the fitted model
        (``means_``, ``covariances_``, ``weights_``, ``precisions_``,
        ``lower_bound_``, ``n_iter_``, ``converged_``, ...) without
        coupling to the adapter.
        """
        return self._model

    def supports_random_state(self) -> bool:
        """GMM consumes ``random_state`` (consumed by sklearn EM init).

        Both ``init_params="kmeans"`` (K-Means seed) and
        ``init_params="random"`` (Dirichlet + Gaussian samples) use
        the framework seed. The framework's runner inspects this
        method to decide whether to pass a seed; returning ``True``
        here means the runner will inject the resolved seed.
        """
        return True
